# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68ff7b6f827a25eb0ef920be8481b81f4fc5b8636170fbff7658eb13f85705498d140957bb79bbf34199c57fd8467eff56178083cfcebae2d6d4488feb8d8e2b

test:
  secret_key_base: bc8ef639091e2ecc557c3065dc8d4caa520f72744bd7615256d5c238c1e3457cf36dc80ed162ed1ea92c028752b84cb8306fa5dc498b6e4a98a064a55fac4c57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
